In [2]:
from environment import Environment
import importlib
import os.path
import random
import re
import sys
import time

import torch
import matplotlib.pyplot as plt
import numpy as np
from unityagents import UnityEnvironment
from collections import deque
import torchvision.transforms as T

In [ ]:
class Args:
    def __init__(self):
        self.train = True
        self.nographics = False
        self.num_eps = 10
        self.rollout = 5
        self.batchsize = 64
        self.pretrain = 1000
        self.num_episodes = 1
        self.max_time = 50
        self.alr = 1e-4
        self.clr = 1e-4
        self.batch = 128
        self.buffer = 100000
        self.C = 4000        
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")        
        self.eval = False
args = Args()
def check_args():
    for arg in vars(args):
        if arg == "sep": continue
        print("{}: {}".format(arg.upper(), getattr(args, arg)))
        
check_args()        


In [ ]:
import environment
importlib.reload(environment)
from environment import Environment


In [ ]:
env = Environment(args)

In [ ]:
for var in vars(env):
    print("{}: {}".format(var.upper(), getattr(env, var)))

In [ ]:
states = torch.from_numpy(env.env_info.vector_observations).float()
# states = [torch.from_numpy(state).float() for state in states]
states

In [ ]:
len(states)

In [18]:
t = torch.zeros(2)
t

tensor([0., 0.])

In [19]:
for i in range(10):
    x = torch.rand(t.shape)
    print(t, x)
    t += x * 2


tensor([0., 0.]) tensor([0.8909, 0.0872])
tensor([1.7818, 0.1743]) tensor([0.4728, 0.3778])
tensor([2.7274, 0.9299]) tensor([0.6056, 0.3013])
tensor([3.9386, 1.5325]) tensor([0.9303, 0.5246])
tensor([5.7992, 2.5816]) tensor([0.2487, 0.0017])
tensor([6.2967, 2.5849]) tensor([0.8254, 0.3856])
tensor([7.9475, 3.3561]) tensor([0.3635, 0.8962])
tensor([8.6744, 5.1484]) tensor([0.9670, 0.0458])
tensor([10.6084,  5.2400]) tensor([0.1980, 0.4771])
tensor([11.0044,  6.1943]) tensor([0.6106, 0.6608])


In [11]:
torch.rand(2)

tensor([0.8970, 0.8181])

In [22]:
x = np.array([11, 2.5])
print(x*2)

[22.  5.]


In [ ]:
env.reset()