In [5]:
import random
import torch

In [4]:
for i in range(20):
    print(random.randrange(4))

0
3
2
1
3
3
3
3
0
3
3
2
1
1
3
3
2
3
1
3


In [21]:
for i in range(20):
    print(torch.LongTensor(1).random_(4))

tensor([3])
tensor([3])
tensor([1])
tensor([3])
tensor([3])
tensor([2])
tensor([0])
tensor([3])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([2])
tensor([1])
tensor([2])
tensor([0])
tensor([1])
tensor([1])


In [10]:
for _ in range(20):
    print(torch.tensor([[random.randrange(4)]]))

tensor([[2]])
tensor([[0]])
tensor([[1]])
tensor([[1]])
tensor([[2]])
tensor([[0]])
tensor([[0]])
tensor([[1]])
tensor([[0]])
tensor([[3]])
tensor([[3]])
tensor([[2]])
tensor([[1]])
tensor([[2]])
tensor([[3]])
tensor([[3]])
tensor([[3]])
tensor([[3]])
tensor([[2]])
tensor([[1]])
